#!/bin/bash

sudo apt update | sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" | sudo apt update
apt-cache policy docker-ce
sudo apt install docker-ce
echo "Введите сайт/IP: "
read site
echo "Введите порт: "
read port
sudo docker run -ti --rm alpine/bombardier -c 1000 -d 3600s -l $site:$port
