#!/bin/bash

sudo apt update | sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
sleep 10
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt key add -
sleep 0.5
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
sudo apt update
sleep 10
apt-cache policy docker-ce
sleep 0.5
sudo apt install docker-ce
